<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Orchid\Platform\Models\Role;

class RolesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $slugs = array(
            "super-yonetici",
            'admin',
            'yonetici',
            'uzman',
            'kurum-uzmani',
            'danisan'

        );

        $names = array(
            "Süper Yönetici",
            'Admin',
            'Yönetici',
            'Uzman',
            'Kurum Uzmanı',
            'Danışan'
        );

        $permissions = [
            //Super Admin
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 1,
                'platform.systems.roles.add' => 1,
                'platform.systems.roles.edit' => 1,
                'platform.systems.roles.remove' => 1,
                'platform.systems.users' => 1,
                'platform.systems.users.add' => 1,
                'platform.systems.users.edit' => 1,
                'platform.systems.users.remove' => 1,
                'platform.systems.settings' => 1,
                'platform.systems.provinces' => 1,
                'platform.systems.provinces.add' => 1,
                'platform.systems.provinces.edit' => 1,
                'platform.systems.provinces.remove' => 1,
                'platform.systems.states' => 1,
                'platform.systems.states.add' => 1,
                'platform.systems.states.edit' => 1,
                'platform.systems.states.remove' => 1,
                'platform.organisations' => 1,
                'platform.organisations.add' => 1,
                'platform.organisations.edit' => 1,
                'platform.organisations.remove' => 1,
                'platform.organisation.specialists' => 1,
                'platform.organisation.specialists.confirm' => 1,
                'platform.organisation.specialists.reject' => 1,
                'platform.organisation.specialists.dismiss' => 1,
                'platform.organisation.canjoin' => 1,
                'platform.organisation.leave' => 1,
                'platform.organisation.cancelRequest' => 1,
                'platform.categories' => 1,
                'platform.categories.add' => 1,
                'platform.categories.edit' => 1,
                'platform.categories.remove' => 1,
                'platform.audios' => 1,
                'platform.audios.add' => 1,
                'platform.audios.edit' => 1,
                'platform.audios.remove' => 1,
                'platform.packages' => 1,
                'platform.packages.add' => 1,
                'platform.packages.edit' => 1,
                'platform.packages.remove' => 1,
                'platform.tests' => 1,
                'platform.tests.add' => 1,
                'platform.tests.edit' => 1,
                'platform.tests.remove' => 1,
                'platform.patients' => 1,
                'platform.patients.add' => 1,
                'platform.patients.edit' => 1,
                'platform.patients.remove' => 1,
                'platform.sessions' => 0,
                'platform.medias' => 1,
                'platform.medias.add' => 1,
                'platform.medias.edit' => 1,
                'platform.medias.remove' => 1,
                'platform.pages' => 1,
                'platform.pages.add' => 1,
                'platform.pages.edit' => 1,
                'platform.pages.remove' => 1,
                'platform.specialists' => 1,
                'platform.specialists.confirm' => 1,
                'platform.tests' => 1,
                'platform.tests.add' => 1,
                'platform.tests.edit' => 1,
                'platform.tests.remove' => 1,
                'platform.canSeeAllPatients' => 1,
                'platform.mytests' => 0,
                'platform.patients.take' => 0,
                'platform.package.assign' => 1,
                'platform.canselectspecialist' => 1,
                'platform.canAssignSpecialist' => 1,
                'platform.blogs' => 1,
                'platform.blogs.add' => 1,
                'platform.blogs.edit' => 1,
                'platform.blogs.remove' => 1,
                'platform.blogs.approve' => 1,
                'platform.sliders' => 1,
                'platform.sliders.add' => 1,
                'platform.sliders.edit' => 1,
                'platform.sliders.remove' => 1,
                'platform.specialists.listing' => 1,
            ],
            //Admin
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 1,
                'platform.systems.roles.add' => 1,
                'platform.systems.roles.edit' => 1,
                'platform.systems.roles.remove' => 1,
                'platform.systems.users' => 1,
                'platform.systems.users.add' => 1,
                'platform.systems.users.edit' => 1,
                'platform.systems.users.remove' => 1,
                'platform.systems.settings' => 0,
                'platform.systems.provinces' => 0,
                'platform.systems.provinces.add' => 0,
                'platform.systems.provinces.edit' => 0,
                'platform.systems.provinces.remove' => 0,
                'platform.systems.states' => 0,
                'platform.systems.states.add' => 0,
                'platform.systems.states.edit' => 0,
                'platform.systems.states.remove' => 0,
                'platform.organisations' => 1,
                'platform.organisations.add' => 1,
                'platform.organisations.edit' => 1,
                'platform.organisations.remove' => 1,
                'platform.organisation.specialists' => 0,
                'platform.organisation.specialists.confirm' => 0,
                'platform.organisation.specialists.reject' => 0,
                'platform.organisation.specialists.dismiss' => 0,
                'platform.organisation.canjoin' => 0,
                'platform.organisation.leave' => 0,
                'platform.organisation.cancelRequest' => 0,
                'platform.categories' => 1,
                'platform.categories.add' => 1,
                'platform.categories.edit' => 1,
                'platform.categories.remove' => 1,
                'platform.audios' => 1,
                'platform.audios.add' => 1,
                'platform.audios.edit' => 1,
                'platform.audios.remove' => 1,
                'platform.packages' => 1,
                'platform.packages.add' => 1,
                'platform.packages.edit' => 1,
                'platform.packages.remove' => 1,
                'platform.tests' => 1,
                'platform.tests.add' => 1,
                'platform.tests.edit' => 1,
                'platform.tests.remove' => 1,
                'platform.patients' => 1,
                'platform.patients.add' => 1,
                'platform.patients.edit' => 1,
                'platform.patients.remove' => 1,
                'platform.sessions' => 0,
                'platform.medias' => 1,
                'platform.medias.add' => 1,
                'platform.medias.edit' => 1,
                'platform.medias.remove' => 1,
                'platform.pages' => 1,
                'platform.pages.add' => 1,
                'platform.pages.edit' => 1,
                'platform.pages.remove' => 1,
                'platform.specialists' => 1,
                'platform.specialists.confirm' => 1,
                'platform.tests' => 1,
                'platform.tests.add' => 1,
                'platform.tests.edit' => 1,
                'platform.tests.remove' => 1,
                'platform.canSeeAllPatients' => 1,
                'platform.mytests' => 0,
                'platform.patients.take' => 0,
                'platform.package.assign' => 1,
                'platform.canselectspecialist' => 1,
                'platform.canAssignSpecialist' => 1,
                'platform.blogs' => 1,
                'platform.blogs.add' => 1,
                'platform.blogs.edit' => 1,
                'platform.blogs.remove' => 1,
                'platform.blogs.approve' => 1,
                'platform.sliders' => 1,
                'platform.sliders.add' => 1,
                'platform.sliders.edit' => 1,
                'platform.sliders.remove' => 1,
                'platform.specialists.listing' => 1,
            ],
            //Manager
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 0,
                'platform.systems.roles.add' => 0,
                'platform.systems.roles.edit' => 0,
                'platform.systems.roles.remove' => 0,
                'platform.systems.users' => 0,
                'platform.systems.users.add' => 0,
                'platform.systems.users.edit' => 0,
                'platform.systems.users.remove' => 0,
                'platform.systems.settings' => 0,
                'platform.systems.provinces' => 0,
                'platform.systems.provinces.add' => 0,
                'platform.systems.provinces.edit' => 0,
                'platform.systems.provinces.remove' => 0,
                'platform.systems.states' => 0,
                'platform.systems.states.add' => 0,
                'platform.systems.states.edit' => 0,
                'platform.systems.states.remove' => 0,
                'platform.organisations' => 0,
                'platform.organisations.add' => 0,
                'platform.organisations.edit' => 0,
                'platform.organisations.remove' => 0,
                'platform.organisation.specialists' => 1,
                'platform.organisation.specialists.confirm' => 1,
                'platform.organisation.specialists.reject' => 1,
                'platform.organisation.specialists.dismiss' => 1,
                'platform.organisation.canjoin' => 0,
                'platform.organisation.leave' => 0,
                'platform.organisation.cancelRequest' => 0,
                'platform.categories' => 0,
                'platform.categories.add' => 0,
                'platform.categories.edit' => 0,
                'platform.categories.remove' => 0,
                'platform.audios' => 0,
                'platform.audios.add' => 0,
                'platform.audios.edit' => 0,
                'platform.audios.remove' => 0,
                'platform.packages' => 0,
                'platform.packages.add' => 0,
                'platform.packages.edit' => 0,
                'platform.packages.remove' => 0,
                'platform.tests' => 1,
                'platform.tests.add' => 0,
                'platform.tests.edit' => 0,
                'platform.tests.remove' => 0,
                'platform.patients' => 0,
                'platform.patients.add' => 0,
                'platform.patients.edit' => 0,
                'platform.patients.remove' => 0,
                'platform.sessions' => 0,
                'platform.medias' => 1,
                'platform.medias.add' => 0,
                'platform.medias.edit' => 0,
                'platform.medias.remove' => 0,
                'platform.pages' => 0,
                'platform.pages.add' => 0,
                'platform.pages.edit' => 0,
                'platform.pages.remove' => 0,
                'platform.specialists' => 0,
                'platform.specialists.confirm' => 0,
                'platform.tests' => 1,
                'platform.tests.add' => 0,
                'platform.tests.edit' => 0,
                'platform.tests.remove' => 0,
                'platform.canSeeAllPatients' => 0,
                'platform.mytests' => 0,
                'platform.patients.take' => 1,
                'platform.package.assign' => 0,
                'platform.canselectspecialist' => 0,
                'platform.canAssignSpecialist' => 0,
                'platform.blogs' => 1,
                'platform.blogs.add' => 1,
                'platform.blogs.edit' => 1,
                'platform.blogs.remove' => 1,
                'platform.blogs.approve' => 0,
                'platform.sliders' => 0,
                'platform.sliders.add' => 0,
                'platform.sliders.edit' => 0,
                'platform.sliders.remove' => 0,
                'platform.specialists.listing' => 0,
            ],
            //Organisation Specialist
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 0,
                'platform.systems.roles.add' => 0,
                'platform.systems.roles.edit' => 0,
                'platform.systems.roles.remove' => 0,
                'platform.systems.users' => 0,
                'platform.systems.users.add' => 0,
                'platform.systems.users.edit' => 0,
                'platform.systems.users.remove' => 0,
                'platform.systems.settings' => 0,
                'platform.systems.provinces' => 0,
                'platform.systems.provinces.add' => 0,
                'platform.systems.provinces.edit' => 0,
                'platform.systems.provinces.remove' => 0,
                'platform.systems.states' => 0,
                'platform.systems.states.add' => 0,
                'platform.systems.states.edit' => 0,
                'platform.systems.states.remove' => 0,
                'platform.organisations' => 1,
                'platform.organisations.add' => 0,
                'platform.organisations.edit' => 0,
                'platform.organisations.remove' => 0,
                'platform.organisation.specialists' => 0,
                'platform.organisation.specialists.confirm' => 0,
                'platform.organisation.specialists.reject' => 0,
                'platform.organisation.specialists.dismiss' => 0,
                'platform.organisation.canjoin' => 1,
                'platform.organisation.leave' => 1,
                'platform.organisation.cancelRequest' => 1,
                'platform.categories' => 0,
                'platform.categories.add' => 0,
                'platform.categories.edit' => 0,
                'platform.categories.remove' => 0,
                'platform.audios' => 0,
                'platform.audios.add' => 0,
                'platform.audios.edit' => 0,
                'platform.audios.remove' => 0,
                'platform.packages' => 0,
                'platform.packages.add' => 0,
                'platform.packages.edit' => 0,
                'platform.packages.remove' => 0,
                'platform.tests' => 1,
                'platform.tests.add' => 0,
                'platform.tests.edit' => 0,
                'platform.tests.remove' => 0,
                'platform.patients' => 1,
                'platform.patients.add' => 1,
                'platform.patients.edit' => 1,
                'platform.patients.remove' => 1,
                'platform.sessions' => 0,
                'platform.medias' => 1,
                'platform.medias.add' => 0,
                'platform.medias.edit' => 0,
                'platform.medias.remove' => 0,
                'platform.pages' => 0,
                'platform.pages.add' => 0,
                'platform.pages.edit' => 0,
                'platform.pages.remove' => 0,
                'platform.specialists' => 0,
                'platform.specialists.confirm' => 0,
                'platform.tests' => 1,
                'platform.tests.add' => 0,
                'platform.tests.edit' => 0,
                'platform.tests.remove' => 0,
                'platform.canSeeAllPatients' => 0,
                'platform.mytests' => 0,
                'platform.patients.take' => 1,
                'platform.package.assign' => 0,
                'platform.canselectspecialist' => 0,
                'platform.canAssignSpecialist' => 0,
                'platform.blogs' => 1,
                'platform.blogs.add' => 1,
                'platform.blogs.edit' => 1,
                'platform.blogs.remove' => 1,
                'platform.blogs.approve' => 0,
                'platform.sliders' => 0,
                'platform.sliders.add' => 0,
                'platform.sliders.edit' => 0,
                'platform.sliders.remove' => 0,
                'platform.specialists.listing' => 0,
            ],
            //Specialist
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 1,
                'platform.systems.roles' => 0,
                'platform.systems.roles.add' => 0,
                'platform.systems.roles.edit' => 0,
                'platform.systems.roles.remove' => 0,
                'platform.systems.users' => 0,
                'platform.systems.users.add' => 0,
                'platform.systems.users.edit' => 0,
                'platform.systems.users.remove' => 0,
                'platform.systems.settings' => 0,
                'platform.systems.provinces' => 0,
                'platform.systems.provinces.add' => 0,
                'platform.systems.provinces.edit' => 0,
                'platform.systems.provinces.remove' => 0,
                'platform.systems.states' => 0,
                'platform.systems.states.add' => 0,
                'platform.systems.states.edit' => 0,
                'platform.systems.states.remove' => 0,
                'platform.organisations' => 1,
                'platform.organisations.add' => 0,
                'platform.organisations.edit' => 0,
                'platform.organisations.remove' => 0,
                'platform.organisation.specialists' => 0,
                'platform.organisation.specialists.confirm' => 0,
                'platform.organisation.specialists.reject' => 0,
                'platform.organisation.specialists.dismiss' => 0,
                'platform.organisation.canjoin' => 1,
                'platform.organisation.leave' => 1,
                'platform.organisation.cancelRequest' => 1,
                'platform.categories' => 0,
                'platform.categories.add' => 0,
                'platform.categories.edit' => 0,
                'platform.categories.remove' => 0,
                'platform.audios' => 0,
                'platform.audios.add' => 0,
                'platform.audios.edit' => 0,
                'platform.audios.remove' => 0,
                'platform.packages' => 0,
                'platform.packages.add' => 0,
                'platform.packages.edit' => 0,
                'platform.packages.remove' => 0,
                'platform.tests' => 1,
                'platform.tests.add' => 0,
                'platform.tests.edit' => 0,
                'platform.tests.remove' => 0,
                'platform.patients' => 1,
                'platform.patients.add' => 1,
                'platform.patients.edit' => 1,
                'platform.patients.remove' => 1,
                'platform.sessions' => 0,
                'platform.medias' => 1,
                'platform.medias.add' => 0,
                'platform.medias.edit' => 0,
                'platform.medias.remove' => 0,
                'platform.pages' => 0,
                'platform.pages.add' => 0,
                'platform.pages.edit' => 0,
                'platform.pages.remove' => 0,
                'platform.specialists' => 0,
                'platform.specialists.confirm' => 0,
                'platform.tests' => 1,
                'platform.tests.add' => 0,
                'platform.tests.edit' => 0,
                'platform.tests.remove' => 0,
                'platform.canSeeAllPatients' => 0,
                'platform.mytests' => 0,
                'platform.patients.take' => 1,
                'platform.package.assign' => 0,
                'platform.canselectspecialist' => 0,
                'platform.canAssignSpecialist' => 0,
                'platform.blogs' => 1,
                'platform.blogs.add' => 1,
                'platform.blogs.edit' => 1,
                'platform.blogs.remove' => 1,
                'platform.blogs.approve' => 0,
                'platform.sliders' => 0,
                'platform.sliders.add' => 0,
                'platform.sliders.edit' => 0,
                'platform.sliders.remove' => 0,
                'platform.specialists.listing' => 0,
            ],
            //Patient
            [
                'platform.index' => 1,
                'platform.systems.attachment' => 0,
                'platform.systems.roles' => 0,
                'platform.systems.roles.add' => 0,
                'platform.systems.roles.edit' => 0,
                'platform.systems.roles.remove' => 0,
                'platform.systems.users' => 0,
                'platform.systems.users.add' => 0,
                'platform.systems.users.edit' => 0,
                'platform.systems.users.remove' => 0,
                'platform.systems.settings' => 0,
                'platform.systems.provinces' => 0,
                'platform.systems.provinces.add' => 0,
                'platform.systems.provinces.edit' => 0,
                'platform.systems.provinces.remove' => 0,
                'platform.systems.states' => 0,
                'platform.systems.states.add' => 0,
                'platform.systems.states.edit' => 0,
                'platform.systems.states.remove' => 0,
                'platform.organisations' => 0,
                'platform.organisations.add' => 0,
                'platform.organisations.edit' => 0,
                'platform.organisations.remove' => 0,
                'platform.organisation.specialists' => 0,
                'platform.organisation.specialists.confirm' => 0,
                'platform.organisation.specialists.reject' => 0,
                'platform.organisation.specialists.dismiss' => 0,
                'platform.organisation.canjoin' => 0,
                'platform.organisation.leave' => 0,
                'platform.organisation.cancelRequest' => 0,
                'platform.categories' => 0,
                'platform.categories.add' => 0,
                'platform.categories.edit' => 0,
                'platform.categories.remove' => 0,
                'platform.audios' => 0,
                'platform.audios.add' => 0,
                'platform.audios.edit' => 0,
                'platform.audios.remove' => 0,
                'platform.packages' => 0,
                'platform.packages.add' => 0,
                'platform.packages.edit' => 0,
                'platform.packages.remove' => 0,
                'platform.tests' => 0,
                'platform.tests.add' => 0,
                'platform.tests.edit' => 0,
                'platform.tests.remove' => 0,
                'platform.patients' => 0,
                'platform.patients.add' => 0,
                'platform.patients.edit' => 0,
                'platform.patients.remove' => 0,
                'platform.sessions' => 1,
                'platform.medias' => 1,
                'platform.medias.add' => 0,
                'platform.medias.edit' => 0,
                'platform.medias.remove' => 0,
                'platform.pages' => 0,
                'platform.pages.add' => 0,
                'platform.pages.edit' => 0,
                'platform.pages.remove' => 0,
                'platform.specialists' => 0,
                'platform.specialists.confirm' => 0,
                'platform.tests' => 0,
                'platform.tests.add' => 0,
                'platform.tests.edit' => 0,
                'platform.tests.remove' => 0,
                'platform.canSeeAllPatients' => 0,
                'platform.mytests' => 1,
                'platform.patients.take' => 0,
                'platform.package.assign' => 0,
                'platform.canselectspecialist' => 0,
                'platform.canAssignSpecialist' => 0,
                'platform.blogs' => 1,
                'platform.blogs.add' => 0,
                'platform.blogs.edit' => 0,
                'platform.blogs.remove' => 0,
                'platform.blogs.approve' => 0,
                'platform.sliders' => 0,
                'platform.sliders.add' => 0,
                'platform.sliders.edit' => 0,
                'platform.sliders.remove' => 0,
                'platform.specialists.listing' => 0,
            ],
        ];

        $roles = [];

        for ($i = 0; $i < count($slugs); $i++) {
            array_push($roles, [
                'slug' => $slugs[$i],
                'name' => $names[$i],
                'permissions' => $permissions[$i],
            ]);
        }

        foreach ($roles as $role) {
            $roles = Role::where('slug', $role['slug'])->first();
            if ($roles) {
                $roles->update($role);
                continue;
            } else {
                Role::create($role);
            }
        }
    }
}
